 <script>
  import { fly } from 'svelte/transition';
	import { quintOut } from 'svelte/easing';
   import Chat  from "../Components/Chat.svelte";
import { onMount } from 'svelte';
   let disabled = ""
  let app = false;
   let info = {}
   let answer = ""
   let inp = ""
   let started = false
   let loading = false;
   let language = "English"
   let translateon = true
   let transloading = false
   let text = {
     "title": "Plan your Coral Gables Day 📝",
     "description":"Interact with GablesGPT an AI that uses <code>GPT3 🤖</code>, <code>YELP 📱</code> , and <code>Salesforce 📈</code> to help you plan and learn about locations in Coral Gables in an innovative way. 🔥🔥🔥",
      "chats": [
     {
       "text": "Hi i'm GablesGPT",
       "from": "bot"
     },
     {
       "text": "I'll help plan your day in Coral Gables.",
       "from": "bot"
     },
     {
       "text": "What do you want to do today?",
       "from": "bot"
     },
      {
       "text": "(Sadly, I cannot respond to you after your initial question 🥺)",
       "from": "bot"
     },
      {
       "text": "But since the ChatGPT API cameout 2 days ago I will be updated soon 😊",
       "from": "bot"
     },
      {
       "text": "PRIVACY CONCERNS: Specific terms generated by your questions will be recorded to salesforce to better improve me 🔥",
       "from": "bot"
     }
   ],
     "button1": "Get Started",
     "button2": "Ask"
   }
   async function translate() {
     transloading = true
     translateon = false
     disabled = "disabled"
       let userLanguage = navigator.language || navigator.userLanguage;
     console.log(userLanguage)
         let url = encodeURI("https://CoralGablesAPI.eduardfaus1.repl.co/translate/"+userLanguage)

     console.log(url)
     let res = fetch(url)
  .then(response => response.json())
  .then((inf) => {
    text = inf
    console.log(text)
    setTimeout(() => {
      disabled = "";
      transloading = true;
                     }, 400)
  })
  }
   async function getAnswer() {
     loading = true;
     started = true;
     info = {}
     let url = encodeURI("https://CoralGablesAPI.eduardfaus1.repl.co/plan-day/"+inp)
     inp = "";
     
     console.log(url)
     let res = fetch(url)
  .then(response => response.json())
  .then((inf) => {
    info = inf.Yelp
    answer = inf.Answer
     setTimeout(()=>{loading = false;}, 50)
  })
  answer = ""
   }
   
</script>
  <div class="hero min-h-screen bg-base-200">
  <div class="hero-content text-center">
    <br>
       <div class="max-w-md">
         {#if translateon}
<button class="btn btn-sm {disabled}" on:click={translate}>Translate  🌍</button>
         {/if}
          {#if transloading}
    <progress class="progress w-56"></progress>
         {/if}
<br>
         <br>
         {#if app == true}
	<div >
    <div class="">
<div style="height: 90%" class=" overflow-y-scroll" id="scrollable-div">
  <!-- Your content here -->
    {#each text.chats as chat}
      <Chat chat={chat.text} from={chat.from}/>
    {/each}
         {#if answer != ""}
        <Chat chat={answer} from={"bot"}/>
          
        {/if}

        
      {#if loading == true}
        <progress class="progress w-56"></progress>
      {:else}
      {#each Object.entries(info) as [key, value]}
      <Chat chat={key} from="me"/>
    

    {#each value as v}
       
<div class="chat chat-start">
  <div class="chat-bubble">
       <a href={v.url}>{v.name}, {"⭐".repeat(v.rating)} </a>
          <a href={v.url}>  
        <img style="height: 75px;" src={v.image_url}/></a>
  </div>
</div>

        {/each}
        {/each}
        <br>
         <input bind:value={inp} class="input ">
      <button on:click={getAnswer} class="btn"> {text.button2}</button>
      {/if}
</div>
  
      <br>
      <br>
      
 
    </div>
	</div>
    {:else}
      <div class="">
      <h1 class="text-5xl font-bold">{text.title}</h1>
      <p class="py-6"> {@html text.description} </p>
      <button class="btn btn-wide" on:click={()=> {app=true}}>{@html text.button1}</button>
    </div>
    {/if}
       </div>
  </div>
</div>
